In [2]:
import pandas as pd
import sys, os
import os.path as osp
from datetime import datetime

In [3]:
df = pd.read_csv('../data/nyc_311_limit.csv', header=None)
df

/Users/admin/opt/anaconda3/envs/DataAnalysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (8,17,20,31,32,34,35,36,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,40990076,11/20/2018 11:18:04 AM,11/21/2018 02:00:41 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758015,-73.938575,"(40.7580151, -73.9385755)"
1,40990078,11/20/2018 11:44:00 AM,11/20/2018 12:00:00 PM,DSNY,Queens East 12,Derelict Vehicles,14 Derelict Vehicles,Street,11433.0,109-02 156 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692565,-73.794982,"(40.6925648, -73.7949815)"
2,40990079,11/20/2018 07:00:00 PM,12/17/2018 01:07:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11234.0,4817 AVENUE K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625734,-73.929306,"(40.6257338, -73.9293057)"
3,40990080,11/20/2018 04:34:00 PM,11/27/2018 12:49:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11230.0,1562 EAST 3 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612385,-73.971536,"(40.6123849, -73.9715356)"
4,40990081,11/20/2018 04:10:00 PM,01/03/2019 12:42:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11207.0,598 PENNSYLVANIA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662621,-73.893503,"(40.6626209, -73.8935035)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7091627,40990071,11/20/2018 10:00:10 PM,11/20/2018 10:45:07 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Bike Lane,Street/Sidewalk,10002.0,385 EAST HOUSTON STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720440,-73.980440,"(40.7204404, -73.9804398)"
7091628,40990072,11/20/2018 10:34:00 PM,11/21/2018 02:25:00 PM,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),NaN,10463.0,3810 BAILEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884336,-73.897524,"(40.8843362, -73.8975242)"
7091629,40990073,11/20/2018 12:00:00 AM,11/27/2018 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Day Care/Nursery,11213.0,275 KINGSTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.670231,-73.942106,"(40.6702312, -73.9421062)"
7091630,40990074,11/20/2018 02:13:02 PM,12/06/2018 03:01:56 PM,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11226.0,311 RUGBY ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642244,-73.965559,"(40.6422438, -73.9655594)"
7091631,40990075,11/20/2018 09:56:36 AM,11/27/2018 03:02:22 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11372.0,35-26 82 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.751447,-73.884631,"(40.7514467, -73.8846307)"

In [8]:
#remove rows with no zipcode or end date
df = df.dropna(axis=0, subset = [2, 8])
df

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,40990076,2018-11-20 11:18:04,11/21/2018 02:00:41 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758015,-73.938575,"(40.7580151, -73.9385755)"
1,40990078,2018-11-20 11:44:00,11/20/2018 12:00:00 PM,DSNY,Queens East 12,Derelict Vehicles,14 Derelict Vehicles,Street,11433.0,109-02 156 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692565,-73.794982,"(40.6925648, -73.7949815)"
2,40990079,2018-11-20 19:00:00,12/17/2018 01:07:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11234.0,4817 AVENUE K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625734,-73.929306,"(40.6257338, -73.9293057)"
3,40990080,2018-11-20 16:34:00,11/27/2018 12:49:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11230.0,1562 EAST 3 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612385,-73.971536,"(40.6123849, -73.9715356)"
4,40990081,2018-11-20 16:10:00,01/03/2019 12:42:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11207.0,598 PENNSYLVANIA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662621,-73.893503,"(40.6626209, -73.8935035)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7091627,40990071,2018-11-20 22:00:10,11/20/2018 10:45:07 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Bike Lane,Street/Sidewalk,10002.0,385 EAST HOUSTON STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720440,-73.980440,"(40.7204404, -73.9804398)"
7091628,40990072,2018-11-20 22:34:00,11/21/2018 02:25:00 PM,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),NaN,10463.0,3810 BAILEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884336,-73.897524,"(40.8843362, -73.8975242)"
7091629,40990073,2018-11-20 00:00:00,11/27/2018 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Day Care/Nursery,11213.0,275 KINGSTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.670231,-73.942106,"(40.6702312, -73.9421062)"
7091630,40990074,2018-11-20 14:13:02,12/06/2018 03:01:56 PM,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11226.0,311 RUGBY ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642244,-73.965559,"(40.6422438, -73.9655594)"
7091631,40990075,2018-11-20 09:56:36,11/27/2018 03:02:22 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11372.0,35-26 82 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.751447,-73.884631,"(40.7514467, -73.8846307)"

In [9]:
#remove rows with wrong zip
df = df[pd.to_numeric(df[8], errors='coerce').notnull()]
df

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,40990076,2018-11-20 11:18:04,11/21/2018 02:00:41 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758015,-73.938575,"(40.7580151, -73.9385755)"
1,40990078,2018-11-20 11:44:00,11/20/2018 12:00:00 PM,DSNY,Queens East 12,Derelict Vehicles,14 Derelict Vehicles,Street,11433.0,109-02 156 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692565,-73.794982,"(40.6925648, -73.7949815)"
2,40990079,2018-11-20 19:00:00,12/17/2018 01:07:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11234.0,4817 AVENUE K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625734,-73.929306,"(40.6257338, -73.9293057)"
3,40990080,2018-11-20 16:34:00,11/27/2018 12:49:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11230.0,1562 EAST 3 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612385,-73.971536,"(40.6123849, -73.9715356)"
4,40990081,2018-11-20 16:10:00,01/03/2019 12:42:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11207.0,598 PENNSYLVANIA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662621,-73.893503,"(40.6626209, -73.8935035)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7091627,40990071,2018-11-20 22:00:10,11/20/2018 10:45:07 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Bike Lane,Street/Sidewalk,10002.0,385 EAST HOUSTON STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720440,-73.980440,"(40.7204404, -73.9804398)"
7091628,40990072,2018-11-20 22:34:00,11/21/2018 02:25:00 PM,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),NaN,10463.0,3810 BAILEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884336,-73.897524,"(40.8843362, -73.8975242)"
7091629,40990073,2018-11-20 00:00:00,11/27/2018 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Day Care/Nursery,11213.0,275 KINGSTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.670231,-73.942106,"(40.6702312, -73.9421062)"
7091630,40990074,2018-11-20 14:13:02,12/06/2018 03:01:56 PM,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11226.0,311 RUGBY ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642244,-73.965559,"(40.6422438, -73.9655594)"
7091631,40990075,2018-11-20 09:56:36,11/27/2018 03:02:22 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11372.0,35-26 82 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.751447,-73.884631,"(40.7514467, -73.8846307)"

In [11]:
df[1] = df[1].apply(lambda x: if !isinstance(x, datetime.datetime): datetime. strptime(x, '%m/%d/%Y %I:%M:%S %p'))
df[2] = df[2].apply(lambda x: if !isinstance(x, datetime.datetime): datetime. strptime(x, '%m/%d/%Y %I:%M:%S %p'))
df

/var/folders/nv/cw3f8ly11rz_fqddf1glkrz00000gn/T/ipykernel_35086/3639201430.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[2] = df[2].apply(lambda x: datetime. strptime(x, '%m/%d/%Y %I:%M:%S %p'))

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,40990076,2018-11-20 11:18:04,2018-11-21 14:00:41,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758015,-73.938575,"(40.7580151, -73.9385755)"
1,40990078,2018-11-20 11:44:00,2018-11-20 12:00:00,DSNY,Queens East 12,Derelict Vehicles,14 Derelict Vehicles,Street,11433.0,109-02 156 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692565,-73.794982,"(40.6925648, -73.7949815)"
2,40990079,2018-11-20 19:00:00,2018-12-17 13:07:00,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11234.0,4817 AVENUE K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625734,-73.929306,"(40.6257338, -73.9293057)"
3,40990080,2018-11-20 16:34:00,2018-11-27 12:49:00,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11230.0,1562 EAST 3 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612385,-73.971536,"(40.6123849, -73.9715356)"
4,40990081,2018-11-20 16:10:00,2019-01-03 12:42:00,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11207.0,598 PENNSYLVANIA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662621,-73.893503,"(40.6626209, -73.8935035)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7091627,40990071,2018-11-20 22:00:10,2018-11-20 22:45:07,NYPD,New York City Police Department,Illegal Parking,Blocked Bike Lane,Street/Sidewalk,10002.0,385 EAST HOUSTON STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720440,-73.980440,"(40.7204404, -73.9804398)"
7091628,40990072,2018-11-20 22:34:00,2018-11-21 14:25:00,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),NaN,10463.0,3810 BAILEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884336,-73.897524,"(40.8843362, -73.8975242)"
7091629,40990073,2018-11-20 00:00:00,2018-11-27 00:00:00,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Day Care/Nursery,11213.0,275 KINGSTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.670231,-73.942106,"(40.6702312, -73.9421062)"
7091630,40990074,2018-11-20 14:13:02,2018-12-06 15:01:56,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11226.0,311 RUGBY ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642244,-73.965559,"(40.6422438, -73.9655594)"
7091631,40990075,2018-11-20 09:56:36,2018-11-27 15:02:22,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11372.0,35-26 82 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.751447,-73.884631,"(40.7514467, -73.8846307)"

In [13]:
df_2020 = df[df[1].dt.year==2020]
df_2020

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
13945,46920293,2020-07-20 10:51:12,2020-09-05 12:32:48,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11234.0,1749 EAST 31 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.611464,-73.939434,"(40.61146397103902, -73.93943433010804)"
71568,46930483,2020-07-21 14:13:58,2020-09-05 13:37:31,MAYORâS OFFICE OF SPECIAL ENFORCEMENT,Mayorâs Office of Special Enforcement,NonCompliance with Phased Reopening,Business not in compliance,Store/Commercial,11210.0,2704 GLENWOOD ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.633719,-73.950720,"(40.633718643537684, -73.9507199410522)"
168691,46997111,2020-07-27 12:56:33,2020-09-05 08:51:14,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11354.0,151-23 28 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.772734,-73.812660,"(40.77273372358884, -73.81266028241241)"
431576,46583727,2020-06-22 18:17:00,2020-06-23 08:59:00,DOT,Department of Transportation,Street Light Condition,Street Light Lamp Missing,NaN,10451.0,2510 PARK AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431681,46576371,2020-06-21 03:30:00,2020-06-22 21:50:00,DOT,Department of Transportation,Street Light Condition,Street Light Cycling,NaN,10031.0,393 EDGECOMBE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6999321,46816724,2020-07-10 10:34:45,2020-08-26 00:00:00,DOB,Department of Buildings,General Construction/Plumbing,Cons - Contrary/Beyond Approved Plans/Permits,NaN,10075.0,1470 1 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.770703,-73.953871,"(40.7707029517019, -73.95387143967716)"
7000892,47117378,2020-08-05 14:55:52,2020-08-13 18:35:49,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11221.0,286 EVERGREEN AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696213,-73.927403,"(40.69621313703872, -73.92740262992484)"
7001481,46830035,2020-07-11 10:53:00,2020-08-21 12:00:00,DSNY,A - Queens,Dirty Conditions,E3 Dirty Sidewalk,Sidewalk,11421.0,89-30 WOODHAVEN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.690430,-73.850419,"(40.69042970218553, -73.85041855768864)"
7079114,46874418,2020-07-16 12:00:23,2020-08-30 17:59:47,HPD,Department of Housing Preservation and Develop...,PLUMBING,BATHTUB/SHOWER,RESIDENTIAL BUILDING,11691.0,19-15 SEAGIRT BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595128,-73.753400,"(40.59512808199396, -73.75339972090964)"
7087032,46876421,2020-07-16 16:55:32,2020-09-05 13:28:38,MAYORâS OFFICE OF SPECIAL ENFORCEMENT,Mayorâs Office of Special Enforcement,NonCompliance with Phased Reopening,Business not in compliance,Store/Commercial,11226.0,1362 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.653459,-73.949866,"(40.65345877011905, -73.94986564239689)"

In [14]:
#Remove data with close date < open date
df_2020 = df_2020[df_2020[2] >= df_2020[1]]
df_2020

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
13945,46920293,2020-07-20 10:51:12,2020-09-05 12:32:48,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11234.0,1749 EAST 31 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.611464,-73.939434,"(40.61146397103902, -73.93943433010804)"
71568,46930483,2020-07-21 14:13:58,2020-09-05 13:37:31,MAYORâS OFFICE OF SPECIAL ENFORCEMENT,Mayorâs Office of Special Enforcement,NonCompliance with Phased Reopening,Business not in compliance,Store/Commercial,11210.0,2704 GLENWOOD ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.633719,-73.950720,"(40.633718643537684, -73.9507199410522)"
168691,46997111,2020-07-27 12:56:33,2020-09-05 08:51:14,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11354.0,151-23 28 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.772734,-73.812660,"(40.77273372358884, -73.81266028241241)"
431576,46583727,2020-06-22 18:17:00,2020-06-23 08:59:00,DOT,Department of Transportation,Street Light Condition,Street Light Lamp Missing,NaN,10451.0,2510 PARK AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431681,46576371,2020-06-21 03:30:00,2020-06-22 21:50:00,DOT,Department of Transportation,Street Light Condition,Street Light Cycling,NaN,10031.0,393 EDGECOMBE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6999321,46816724,2020-07-10 10:34:45,2020-08-26 00:00:00,DOB,Department of Buildings,General Construction/Plumbing,Cons - Contrary/Beyond Approved Plans/Permits,NaN,10075.0,1470 1 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.770703,-73.953871,"(40.7707029517019, -73.95387143967716)"
7000892,47117378,2020-08-05 14:55:52,2020-08-13 18:35:49,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11221.0,286 EVERGREEN AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696213,-73.927403,"(40.69621313703872, -73.92740262992484)"
7001481,46830035,2020-07-11 10:53:00,2020-08-21 12:00:00,DSNY,A - Queens,Dirty Conditions,E3 Dirty Sidewalk,Sidewalk,11421.0,89-30 WOODHAVEN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.690430,-73.850419,"(40.69042970218553, -73.85041855768864)"
7079114,46874418,2020-07-16 12:00:23,2020-08-30 17:59:47,HPD,Department of Housing Preservation and Develop...,PLUMBING,BATHTUB/SHOWER,RESIDENTIAL BUILDING,11691.0,19-15 SEAGIRT BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595128,-73.753400,"(40.59512808199396, -73.75339972090964)"
7087032,46876421,2020-07-16 16:55:32,2020-09-05 13:28:38,MAYORâS OFFICE OF SPECIAL ENFORCEMENT,Mayorâs Office of Special Enforcement,NonCompliance with Phased Reopening,Business not in compliance,Store/Commercial,11226.0,1362 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.653459,-73.949866,"(40.65345877011905, -73.94986564239689)"

In [29]:
a,_= df_2020.shape
b,_ = df.shape
print(f'2020: {a}; no: {b}')

2020: 1887577; no: 7091632

In [15]:
df[1].dtypes

dtype('<M8[ns]')

In [16]:
df_2020.to_csv("../data/nyc_311_limit_2020.csv", index=False, header=None)